### ISSUE TITLE
bug: Opening a finder twice leaves floating windows opened

### ISSUE THREAD

**Issue by Luxed** [nvim-lua/telescope.nvim#102]
When you are in the `find_files` finder, go into normal mode and open `find_files` again, everything will be in a bugged state where you cannot do anything.
Closing using `<esc>` or `<c-c>` will only close the "Find Files" window. Pressing `<CR>` on a result will populate the "Find Files" window.

**Comment by tjdevries** [comment]
Ah, so just running it again while one is currently open?

I'm assuming what you'd like to have happen is we close down the last one and then start fresh w/ a new one?

**Comment by Luxed** [comment]
Either that (which might be the easiest way to do it) or we reuse what has already been opened, but then I'm guessing we would need a global state for telescope and since the configuration could vary wildly from finder to finder, closing the older ones might be a simpler solution.

**Comment by tjdevries** [comment]
OK, got this working for me w/ latest commit. Let me know if it doesn't work for you.
