### ISSUE TITLE
Long running grep causes `not enough memory` error

### ISSUE THREAD

**Issue by sunjon** [nvim-lua/telescope.nvim#103]
![nvim_OOM](https://user-images.githubusercontent.com/1448118/93660895-cdc9b780-fa53-11ea-9704-5822b8ed02f8.gif)

**Comment by tjdevries** [comment]
Yeah, I'm working on tracking down some memory leaks... Hopefully I can fix or prevent this.

You can set a maximum number of results, which should at leadt make it not crash.

**Comment by tjdevries** [comment]
Does this still happen with updated plenary and telescope and nvim :)

**Comment by sunjon** [comment]
sorry for the delayed response.
Nope, Don't seem to be able to reproduce anymore.
Closing the issue, thanks!
