### ISSUE TITLE
1 buffer deleted messages when closing telescope

### ISSUE THREAD

**Issue by tami5** [nvim-lua/telescope.nvim#105]
Hey there, I'm ready to switch to telescope and I think its awesome. I have one issue though, everytime I close the buffer I get few lines of 1 buffer deleted. Any way to omit this messages, thanks

**Comment by tami5** [comment]
Caused by a plugin I have installed by @qpkorr for deleting buffers without closing the split.

Thanks

**Comment by tami5** [comment]
Yah even after uninstalling the plugin I still have the issue. So this issue is valid, I think

**Comment by tjdevries** [comment]
What's the exact error message? And whenever you close by exiting and accepting a result?

**Comment by tami5** [comment]
Yah the issue happens when ever I hit search with telescope, it happens when existing and accepting results. Usually when a buffer or popup get deleted I have this message telling me a buffer deleted which should be disabled with telescope

**Comment by tjdevries** [comment]
I hope this fixed the issue with latest commit.

Let me know if that's not the case.

**Comment by FabioRamatis** [comment]
![Screen Shot 2020-09-22 at 19 30 09](https://user-images.githubusercontent.com/69860869/93943983-07c3e380-fd0a-11ea-8e4b-00c5cf98a094.png)

I'm having the same issue(I installed this plugin literally right now via vim-plug)
This happens all time I select an line search to effectively go to the file

**Comment by tjdevries** [comment]
Which builtin did you do to make it happen? I will try and reproduce again.

**Comment by FabioRamatis** [comment]
I just installed this plugins: 

Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-lua/telescope.nvim'

and run on command mode
```
:lua require('telescope.builtin').git_files()
```

my version output: 
![Screen Shot 2020-09-23 at 15 22 42](https://user-images.githubusercontent.com/69860869/94053366-a145d080-fdb0-11ea-8419-ba211b2ff8fe.png)

**Comment by tjdevries** [comment]
Thanks @FabioRamatis . Do you have your init.vim anywhere? Perhaps there is a setting I don't know about that I can set to replicate this as well. Otherwise I will just push a bunch of changes to try and make the deletes silent :laughing:

**Comment by FabioRamatis** [comment]
Yeah totally, it's on: https://github.com/cherryramatis/vim-sorcerer/blob/master/init.vim

I just have init.vim and better-defaults.vim on vimscript

The rest is build with fennel, but it's readable 😂

I'm thinking that might be something with better-defaults.vim because i just copy and paste from https://github.com/liuchengxu/vim-better-default

**Comment by tjdevries** [comment]
Can you try setting `set report=2` in your config after you source the defaults?

I think that's the problem -- I'm not sure how to get it to NOT show the message with that setting. ( and I don't know why anyone would set that as a good default :laughing: )

**Comment by tjdevries** [comment]
After looking some more, it's not clear to me that it's possible to clear those messages from my end. Perhaps I should warn users if they have report set? I don't know... Open to suggestions.

**Comment by tjdevries** [comment]
I have added a warning message when using telescope if you have `report` set to an invalid value.

I do not like setting global options for people in a plugin. They should either change their settings OR convince me that I should find a way to support `report=0` :laughing: I do not know of any reasons.

**Comment by Julian** [comment]
Also trying treesitter for the first time and finding it complaining at me about my report setting :)

Not sure I'll have any more luck at figuring out how to support `report=0`, will have a quick look, but may be nice if the warning at least links to this issue or says something about why treesitter doesn't work with `report=0` at the minute. (Happy to send a PR rewording obviously if that's agreeable)

**Comment by Julian** [comment]
Attempted re-fix in #282.
