### ISSUE TITLE
why preview dos not wrok!

### ISSUE THREAD

**Issue by lemontghe** [nvim-lua/telescope.nvim#109]
i installed bat and all of the dependencies but my preview doesnt since to work.
![where_is_the_preview](https://i.imgur.com/oFOl0LF.png)

**Comment by tjdevries** [comment]
Hi :) 

Can you paste your configuration and the command that you're running?

Thanks.

**Comment by lemontghe** [comment]
" telescope
" {{{
" nnoremap <Leader>p <cmd>lua require'telescope.builtin'.git_files{}<CR>
nnoremap <Leader>p <cmd>lua require'telescope.builtin'.find_files{}<CR>

nnoremap <silent> gr <cmd>lua require'telescope.builtin'.lsp_references{}<CR>
nnoremap <Leader>en <cmd>lua require'telescope.builtin'.find_files{ cwd = "~/.config/nvim/" }<CR>
nnoremap <C-f> :lua require'telescope.builtin'.find_files(require('telescope.themes').get_dropdown({}))<cr>

" }}}

**Comment by lemontghe** [comment]
could it have something with environment variables

**Comment by lemontghe** [comment]
or shell
i'm using fish as my default shell

**Comment by lemontghe** [comment]
yeah i changed my shell and it stupidly works! [gaj](https://i.imgur.com/bJ26PwL.png)
also it's should be have an option to change the bat theme rather than changing the source code.
