### ISSUE TITLE
Comarison to vim-clap

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [nvim-lua/telescope.nvim#121]
I was wondering how comparable this is to vim-clap? I was also wondering if you have considered using [maple](https://github.com/liuchengxu/vim-clap/blob/master/INSTALL.md#maple-binary) as a provider.

**Comment by tjdevries** [comment]
Hey @Th3Whit3Wolf 

I'd say they are similar in some ways, but `telescope.nvim` is Neovim only, is written in Lua, and has a different architecture.

They accomplish a lot of the same goals and vim-clap is really cool :)

I don't know exactly what you're interested in how they compare, but at the moment I'll close this issue (you can ask me more here if you're interested).

**Comment by tjdevries** [comment]
As for `maple`, I haven't tested anything out with it yet, but we could probably use it, yeah! Before using an external process, I want to implement some more fixes for the `picker` first.
