### ISSUE TITLE
Preview not working when window size is small

### ISSUE THREAD

**Issue by quantum-booty** [nvim-lua/telescope.nvim#122]
![image](https://user-images.githubusercontent.com/28958399/94202836-4e564100-feb6-11ea-8e11-44bf79c6176e.png)
On 1440p, the preview works for double vertical split, but not for triple split.

**Comment by tjdevries** [comment]
Can you send the dimensions of your terminal and the configuration that you have?

Also, can you tell me the value of your "&shell"?

**Comment by quantum-booty** [comment]
&shell=bin/bash
I don't know the dimensions but my monitor is 27" and 1440p, and this is roughly the point at which the preview stops working:
![image](https://user-images.githubusercontent.com/28958399/94255813-be011600-ff20-11ea-9874-f59e5394c1f0.png)

**Comment by bew** [comment]
@quantum-booty I thinks @tjdevries need the size in nulber of cells, in a shell you can display the cell dimensions with `echo $LINES $COLUMNS` iirc

**Comment by quantum-booty** [comment]
@bew Thanks. The dimensions when I don't get preview are 63x120.

**Comment by tjdevries** [comment]
Is this still happening? Made some changes in regards to previewers.

**Comment by quantum-booty** [comment]
@tjdevries It's still happening.

**Comment by tjdevries** [comment]
We may have pushed a fix for this, it's a bit hard to confirm (since I haven't seen this happen to me).

Let me know if you are still having this. If not, we can close :grin:

**Comment by quantum-booty** [comment]
@tjdevries Thank you so much, its working now!
