### ISSUE TITLE
Opening live grep then git find breaks the first popup

### ISSUE THREAD

**Issue by chrisburgin95** [nvim-lua/telescope.nvim#123]
1. Open `live grep`
2. Hit ESC
3. Open `git find` without closing the `live grep` popup
4. Close git find with `:q` 

You will be left with a portion of the `live grep` popup still open but are  able to close it. The border around the input area will also be gone.

![Screenshot from 2020-09-25 08-14-55](https://user-images.githubusercontent.com/1278846/94266000-73bf6b00-ff07-11ea-8269-6c78ed0e0adf.png)

**Comment by Luxed** [comment]
Are you sure you are using the latest version?
This was already reported in #102.

**Comment by chrisburgin95** [comment]
@Luxed Your right already reported and fixed! Thanks and closing!
