### ISSUE TITLE
lsp_workspace_symbols symbol finder failed with error message

### ISSUE THREAD

**Issue by ray-x** [nvim-lua/telescope.nvim#125]
telescope failed when `lua require'telescope.builtin'.lsp_workspace_symbols{}` for golang project.

error message:
```
E5108: Error executing lua /usr/local/share/nvim/runtime/lua/vim/lsp/util.lua:1352: bad argument #1 to 'ipairs' (table expected, got nil)            
Press ENTER or type command to continue                                        
````

Language server:  gopls

Did some tracing shows that 
```lua
local results_lsp = vim.lsp.buf_request_sync(0, "workspace/symbol", params, 1000)
``` 
return a non-nil table, but the table do not have `result` field.

This part works fine with lua lsp. So I believe that reason is gopls does not support empty symbol name as search input.

Is it possible to configure the plugin to search word under cursor as a workaround?

**Comment by smartding** [comment]
same problem here

**Comment by tjdevries** [comment]
I think this is fixed now -- can either of you confirm? Thanks :)

**Comment by smartding** [comment]
> I think this is fixed now -- can either of you confirm? Thanks :)

I open a golang project, but nothing happened when I run `:lua require('telescope.builtin').lsp_workspace_symbols{}` in neovim command. Good news is the error message is gone.

gopls expect something in your query when you ask it for workspace_symbols (gopls will return empty result if it receives an empty query). So I think after I run `lsp_workspace_symbols{}` telescope should pop up a window asking for something as query key words. Then as I type in something, telescope should interactively update the result.

**Comment by tjdevries** [comment]
Hmm interactive would be very hard -- the LSP can take a LOOONNNGGG time to send back the result.

You can make a mapping that asks you for a prompt / uses the current word / etc. to populate the values. It is configurable.

**Comment by smartding** [comment]
> Hmm interactive would be very hard -- the LSP can take a LOOONNNGGG time to send back the result.
> 
> You can make a mapping that asks you for a prompt / uses the current word / etc. to populate the values. It is configurable.

Maybe, you can pop up the telescope window, wait for my query keyword and after I press enter, you send the query to gopls. There would be no interaction this way.

**Comment by tjdevries** [comment]
You can already do this with vim.fn.input, I don't think it requires changes to core.

**Comment by smartding** [comment]
> You can already do this with vim.fn.input, I don't think it requires changes to core.

vim.fn.input requires you to type into vim command line area? I was hoping I can type the query in telescope, so that the workflow is not broken into 2 parts.

**Comment by tjdevries** [comment]
Hmmm, it would be difficult to make work I think. You could write something that makes floating prompt or something, but it would do the same thing I think.

If you want, you can open new issue about that part.
