### ISSUE TITLE
File opened from telescope has absolute path

### ISSUE THREAD

**Issue by Anrock** [nvim-lua/telescope.nvim#126]
1. `cd example_dir`
2. `nvim`
3. `lua require'telescope.builtin'.find_files{}`
4. Select `some_nested_dir/example_file`
5. Check path in status line of opened file

Expected: `some_nested_dir/example_file` (relative)
Actual: `/home/username/ ... /example_dir/nested_dir/example_file` (absolute)

Some details:
* `set statusline?` => `statusline=`
* If file was previously opened via `:e nested_dir/example_file`, then window with file was closed and file was reopened via telescope - path is relative.

**Comment by tjdevries** [comment]
I think I got this in the last commit. Could you check if it works for you now?

**Comment by Anrock** [comment]
Seems to be fixed, thanks!

**Comment by marcelfahle** [comment]
Hi @tjdevries , just a little addon to this issue: For me, the problem still persists with "some" filenames. In my case, I have a file with square brackets in the name (common for example in Next.js). If I open such a file, the path to the buffer is absolute, any other file works just fine. 
And, as OP mentioned, when I first open the file by other means (:e or nerdtree) it works fine as well. 
See GIF attached:

![CleanShot 2021-09-02 at 10 27 23](https://user-images.githubusercontent.com/181004/131801185-ae31e65a-d9ec-49fc-86da-39e7a7c15d69.gif)

**Comment by marcelfahle** [comment]
I updated telescope this morning, and it's working great now! Thanks Teej! <3

**Comment by Hubro** [comment]
I am still having this issue, but not as straight forward. Some times files are opened with a path relative to the working directory, other times they are opened relative to my home directory, starting with `~/`. Both of these behaviors happen in the same repo, both using `:Telescope find_files`.

After some testing, it seems like all Python files (`*.py`) are opened relative to my home directory while everything else is opened using the relative path.

**Comment by Conni2461** [comment]
@Hubro open a new issue filling out the bug template and providing the steps to reproduce this issue. Make sure all your plugins are up to date before doing so

**Comment by Hubro** [comment]
> @Hubro open a new issue filling out the bug template and providing the steps to reproduce this issue. Make sure all your plugins are up to date before doing so

After some more testing, it turns out it's the pyright language server that does this. The first Python file I open has the correct path, every subsequent Python file I open is reopened using the path relative to home (`~/...`) for some reason.
