### ISSUE TITLE
aesthetic suggestions

### ISSUE THREAD

**Issue by pwntester** [nvim-lua/telescope.nvim#128]
Thanks for the awesomeness of this plugin and for adding so many options to configure it. Let me suggest some additional options :)

This is how my current fuzzy finder looks like (a tailored version of norcalli's ui.nvim):

<img width="939" alt="image" src="https://user-images.githubusercontent.com/125701/94486362-9b505500-01df-11eb-8c64-baa84f96305c.png">

The closest I got to this with telescope was this:

<img width="986" alt="image" src="https://user-images.githubusercontent.com/125701/94690581-97801800-0330-11eb-80dc-a213c627b6e5.png">

 which is using the following options to get the "fake" padding instead of hard borders:

```
  local dropdown_opts = require('telescope.themes').get_dropdown({
    winblend = 10;
    borderchars = {
      prompt = {'▀', '▐', '▄', '▌', '▛', '▜', '▟', '▙' };
      results = {' ', '▐', '▄', '▌', '▌', '▐', '▟', '▙' };
    }
  })
```

My current problems are:

1. when `prompt` is empty, the surrounding spaces are left in the border win which as you can see in the screenshot break the upper padding
2. It would be nice to add a new highlight group for the `>` char in the selected line
3. It would be nice to have an option to draw the prompt at the the prompt win, rather than at the prompt border win
4. As you can see in my screenshot, I added a feature to ui.nvim to display right-aligned virtual text that accepts a function that prints some text at the right of the prompt window (eg: number of total matches, number of results fitting in the window, etc)

Thanks again for the plugin!

**Comment by pwntester** [comment]
also, I cant seem to resize the height of the results window which seems to be hardcoded to 15 (https://github.com/nvim-lua/telescope.nvim/blob/master/lua/telescope/pickers/layout_strategies.lua#L141)

**Comment by pwntester** [comment]
I saw you already implemented 4), nice! will it be possible to pass a function to generate the virtual text?

I submitted #135 for 2) and [#19](https://github.com/nvim-lua/plenary.nvim/pull/19) for 1)

I saw you already implemented 3) through `prompt_prefix` but it is commented out/disabled. I guessed that for a good reason so didnt touch that one for now.

**Comment by rockerBOO** [comment]
I look to add an option to tighten up the space between the prompt and the results so it looks tighter. 

I also will add an option to change the number of results on list. Need to think of a good name. (I thought it was already an option of opts.max_results but I will see what happened)

**Comment by rockerBOO** [comment]
I have made those changes in #143 

`get_dropdown{ results_height = 5, border = false}` will remove all the borders and collapse the prompt and results now. 

Now that I'm thinking of it, it doesn't exactly solve your problem since you're using characters to apply another border. I may need to make another option to collapse even if you have borders.

**Comment by pwntester** [comment]
No description provided.

**Comment by rockerBOO** [comment]
@tjdevries will know more about the `prompt_prefix`. Not quite sure about where it's at.

**Comment by tjdevries** [comment]
I was messing around with some stuff for a prompt, but I got a race condition I couldn't figure out when starting the search intermittently where the results wouldn't show up right away.

I can maybe merge it later and see if other people have the same problem. I can turn off the feature via a flag or something.

**Comment by tjdevries** [comment]
As for the status text, you can pass `get_status_text` (which is a function that takes a picker and returns a string) in your defaults/options to change the value.

The default looks like this:

```lua
  set("get_status_text", function(self) return string.format("%s / %s", self.stats.processed - self.stats.filtered, self.stats.processed) end)
```

@pwntester can you make separate issues for the remaining items? I'm not 100% sure what's left for this one anymore :laughing:

**Comment by pwntester** [comment]
@tjdevries oh nice, didnt realize there was an option for that, thanks!

As for the remaining isses, there are only two and both of them have PRs, so opening a new issue may not be necessary (let me know otherwise :D)

https://github.com/nvim-lua/plenary.nvim/pull/19
https://github.com/nvim-lua/telescope.nvim/pull/154

**Comment by tjdevries** [comment]
That does look really pretty :) very cool.

Can you put that picture somewhere on the wiki? Just make a new page of gallery or something, just to show pretty examples.

**Comment by tjdevries** [comment]
(and can we close now?)

**Comment by tami5** [comment]
@pwntester That looks really goood, can you share you configuration. Thanks

**Comment by pwntester** [comment]
> @pwntester That looks really goood, can you share you configuration. Thanks

Sure, you can find my telescope (and rest of nvim) config in my [dots repo](https://github.com/pwntester/dotfiles/blob/master/config/nvim/lua/plugins/telescope.lua)

**Comment by pwntester** [comment]
> That does look really pretty :) very cool.
> 
> Can you put that picture somewhere on the wiki? Just make a new page of gallery or something, just to show pretty examples.

Thanks, will do!

**Comment by pwntester** [comment]
> Can you put that picture somewhere on the wiki? Just make a new page of gallery or something, just to show pretty examples.

Noob question ahead ... how can I contribute to the wiki? It seems like I cant send PRs to it

**Comment by tjdevries** [comment]
I think you should just be able to edit it now. I didn't realize there was a super secret hidden button not labeled or nested under wikis for allowing non-members to edit. :laughing:

**Comment by pwntester** [comment]
Uploading these images here for the gallery, for some reason I cannot upload them directly to the wiki, and I prefer keeping them through this issue than using imgur or something like that

![](https://user-images.githubusercontent.com/125701/95586779-6f379e00-0a41-11eb-8d36-88e10c431836.png)
![](https://user-images.githubusercontent.com/125701/95586787-72328e80-0a41-11eb-86e3-ec4ba66866f5.png)
