### ISSUE TITLE
No quickfix items due to empty qflist

### ISSUE THREAD

**Issue by himansingh241** [nvim-lua/telescope.nvim#13]
This returns an empty list 
https://github.com/nvim-lua/telescope.nvim/blob/6b066cf9e866729b9c8292d7ab3e8071abdd7d45/lua/telescope/builtin.lua#L162

But on calling `getloclist()` I get the list of errors in the file. 

I can create a PR for this but I'm confused that should I just replace it with - 
```
  local locations = vim.fn.getloclist(0)
```
Or is there any other better way for this?

**Comment by tjdevries** [comment]
Perhaps we should add an option for checking `loclist` if `qflist` is empty. They are two different lists and get populated separately.

Or we could have two different `builtins` for them. Either would be fine with me I think.

**Comment by himansingh241** [comment]
Fixed - https://github.com/nvim-lua/telescope.nvim/pull/17
