### ISSUE TITLE
Add example of using custom mappings

### ISSUE THREAD

**Issue by krkhan** [nvim-lua/telescope.nvim#131]
Something like this doesn't work:

```
local actions = require('telescope.actions')
local telescope = require('telescope')
telescope.setup {
  defaults = {
    default_mappings = {
      i = {
        ["<C-i>"] = actions.goto_file_selection_split,
        ["<C-s>"] = actions.goto_file_selection_vsplit,
      },
      n = {
        ["<C-i>"] = actions.goto_file_selection_split,
        ["<C-s>"] = actions.goto_file_selection_vsplit,
      },
    },
  }
}
```

A working example in the README would be great.

**Comment by rockerBOO** [comment]
I will try to get the mappings in the docs on Tuesday. I dont use custom mappings so I don't know the exact way to do it. 

In the meantime check out `attach_mappings = function(prompt_bufnr, mapper) end`. That option should allow you to set your own mappings.

https://github.com/nvim-lua/telescope.nvim/blob/054bd34498e3e6cfef8f8332fe8de4c0463914dd/lua/telescope/builtin.lua#L90

**Comment by rockerBOO** [comment]
To follow up I will try to add these docs tonight.

**Comment by tjdevries** [comment]
OK, pushed something that should allow you to do this, let me know if it doesn't actually solve your problem. Update is in the readme now as well!

**Comment by krkhan** [comment]
@tjdevries @rockerBOO thanks! I updated the plugin and the example from README works just fine. Although for some strange reason the ANSI escape sequences are not getting interpreted correctly anymore. Opened issue #160 for that; closing this one.
