### ISSUE TITLE
buffers builtin not triggering BufEnter when switching buffers

### ISSUE THREAD

**Issue by pwntester** [nvim-lua/telescope.nvim#140]
Hi,

Not sure if this is a Telescope problem, but If I set the following autocmds:

```
vim.cmd [[ au BufEnter * nested echom 'entered '..expand('<afile>')  ]]
vim.cmd [[ au BufLeave * nested echom 'leaving '..expand('<afile>')  ]]
```

And then open a couple of files(A and B) and from A I use the buffers' builtin to switch to B, I dont get the 'entered B' message.

Thanks

**Comment by tjdevries** [comment]
Think this is fixed now, was trying to be too smart w/ stuff. Shoulda just been dumber :laughing:

**Comment by pwntester** [comment]
oh, so `nvim_win_set_buf` does not trigger `BufEnter`? is that a bug or expected behavior?

**Comment by tjdevries** [comment]
It says "No side effects" in the docs... so I guess so
