### ISSUE TITLE
Is the project ded??? 

### ISSUE THREAD

**Issue by tjdevries** [nvim-lua/telescope.nvim#141]
😂

I'm just kidding. Me and my wife are having a baby in the next two weeks, Lord willing. So I will not be responding very often to issues or PRs in the next couple weeks. I'll resume more stuff once life returns back to normal (or once I learn to manage haha)

Just wanted to give people an update. Will probably still do some stuff but didn't want people to be confused. 

Thanks for understanding and being patient! Happy coding!

**Comment by norcalli** [comment]
As an avid open source user, I'm shocked and appalled by the fact that this man is willing to put his wife and unborn child above my needs as a user. Unsubscribed.

**Comment by teto** [comment]
They are building the next FOSS contributors for telescope v2. Is there anyone in charge in your potential absence (I am sure you are going to manage :p) ?

**Comment by bfredl** [comment]
Just fork the project as neotelescope already (filter the commits to make
merge back as hard as possible)

Den sön 4 okt. 2020 12:07Matthieu Coudron <notifications@github.com> skrev:

**Comment by tjdevries** [comment]
@rockerBOO has merge permissions and has my permission to do things he thinks are smart.

I'm not committing him to anything of course 😂 but he's been a huge help so far and has the ability to merge stuff, answer questions, etc.

**Comment by tjdevries** [comment]
We had the baby :) He's doing great. I'll be around more often again :)
