### ISSUE TITLE
highlight match in the list while typing

### ISSUE THREAD

**Issue by tami5** [nvim-lua/telescope.nvim#146]
Hi there, is it possible to highlight match? For examples say you are in your dotfiles and you type lua, you would see dir/file."lua" highlighted or flua, you would see flua highlight.
![](https://camo.githubusercontent.com/91680e2844f5b96d86ad8933628ba78d808cdfcf/687474703a2f2f64756d702e6269746368656573652e6e65742f696d616765732f75736964616e752f68656c6d2e706e67)

Thanks

**Comment by clason** [comment]
This is already possible, just not enabled out of the box -- you just need to set the `TelescopeMatching` highlight group to something you like, e.g.,
```vim
hi! link TelescopeMatching Statement
```

**Comment by tami5** [comment]
Nice, Thanks a lot
