### ISSUE TITLE
move_selection_next/previous should cycle

### ISSUE THREAD

**Issue by tami5** [nvim-lua/telescope.nvim#147]
Hi there, so I'm currently testing and playing with telescope and I notice when opening a new window or having only few options,  hitting C-n, doesn't cycle, i.e. it doesn't got the first item of the list, rather selection indicator disappears..

Thanks

**Comment by tjdevries** [comment]
OK, now if you do (in your setup) `scroll_strategy = 'cycle',` then it will cycle the results.

I didn't do this by default cause I think it's confusing and later we will try and implement actually scrolling down through the results, but it's too hard at the moment.

**Comment by tami5** [comment]
Thanks a lot @tjdevries
