### ISSUE TITLE
Error: on builtin.live_grep(): Failed to save undo information 

### ISSUE THREAD

**Issue by tami5** [nvim-lua/telescope.nvim#149]
Hi there, when using the builtin `live-grep()` search, and try to delete a work with `C-w` or `backspace` I get the following error:

![](https://i.ibb.co/YpkTFj4/pic-window-201007-0659-34.png)

I have undofile set and I added `BufWritePre TelescopePrompt setlocal noundofile` but it didn't fix the issue.

Also, jk in normal mode doesn't work in normal mode with live_grep

Thanks

**Comment by tami5** [comment]
Seems thing to be working with no problem that I change  prompt_position and
 sorting_strategy to default settings. However, still j/k doesn't work in normal mode as pressing j or k returns me to insert mode.

**Comment by tjdevries** [comment]
is this still happening? Also, I think you have set your mappings to not do anything in normal mode, according to what I saw in your other thread.

**Comment by tjdevries** [comment]
(If this is still happening, can you paste your telescope config and then builtin that you used to make this happen?)

**Comment by tami5** [comment]
Sure thing, I'm having a huge amount of issues with live_grep I'm not sure why, in the next comment I will expand on

**Comment by tami5** [comment]
@tjdevries , I'm using bat. Now another issue I have is the live_grep command open in normal mode, and after going insert and typing few words it goes back to to normal mode. and if I just kept on pressing a letter for example k, it would jump between moving selection and typing the latter /normal->insert->normal/ Its so wired. 

```
local defaults = {
  winblend = 5,
  shorten_path = false,
  prompt_position = 'bottom',
  sorting_strategy = 'descending',
  default_mappings = {
    i = {
      ['<C-j>'] = require('telescope.actions').move_selection_next,
      ['<C-n>'] = require('telescope.actions').move_selection_next,
      ['<C-k>'] = require('telescope.actions').move_selection_previous,
      ['<C-p>'] = require('telescope.actions').move_selection_previous,
      ['<C-b>'] = require('telescope.actions').preview_scrolling_up,
      ['<C-f>'] = require('telescope.actions').preview_scrolling_down,
      ['<CR>']  = require('telescope.actions').goto_file_selection_edit,

      ['<C-v>'] = require('telescope.actions').goto_file_selection_vsplit,
      ['<C-s>'] = require('telescope.actions').goto_file_selection_split,
      ['<C-t>'] = require('telescope.actions').goto_file_selection_tabedit,
      ['<C-c>'] = require('telescope.actions').close,
      ['<esc>'] = require('telescope.actions').close,
    },
    n = {
      ['<CR>']  = require('telescope.actions').goto_file_selection_edit,
      ['<C-v>'] = require('telescope.actions').goto_file_selection_vsplit,
      ['<C-s>'] = require('telescope.actions').goto_file_selection_split,
      ['<C-t>'] = require('telescope.actions').goto_file_selection_tabedit,
      ['<esc>'] = require('telescope.actions').close,

      ["j"] = require('telescope.actions').move_selection_next,
      ["k"] = require('telescope.actions').move_selection_previous,

      ['<C-b>'] = require('telescope.actions').preview_scrolling_up,
      ['<C-f>'] = require('telescope.actions').preview_scrolling_down,
    },
  },
}

```

**Comment by tami5** [comment]
@tjdevries hopefully this recording would show more of the issue I'm having https://asciinema.org/a/A5UaKYJT33tdWoDdUSRlxnyzF

Basically C-w, deleting the previous word breaks grep

**Comment by tami5** [comment]
Also, when going to normal mode and pressing j or k or even arrows, I get back to insert mode

**Comment by tami5** [comment]
Tried adding `autocmd! BufEnter,BufReadPre,BufReadPost,BufWinEnter TelescopePrompt setlocal noundofile` but still the same issue.

**Comment by tjdevries** [comment]
Have you rebuilt the latest nvim nightly recently?

it does appear some stuff is broken with live_grep, so I will try and figure out how to fix some of them and may solve this along the way :) we will have to see though.

**Comment by tami5** [comment]
Hey @tjdevries , I believe it is. running version command produce the following:

```
NVIM v0.5.0-772-g2786d96fa
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong
 -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travi
s/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/n
eovim/build/include
Compiled by travis@travis-job-98d0785d-0a81-44d5-9058-f7934f9e4ac0

Features: +acl +iconv +tui
See ":help feature-compile"
```

**Comment by tjdevries** [comment]
Fixed it w/ deps & here :)
