### ISSUE TITLE
Center layout with default result height throws error

### ISSUE THREAD

**Issue by parmort** [nvim-lua/telescope.nvim#155]
Not sure how to fix, but using the following config throws an arithmetic error.

```lua
require'telescope'.setup{ defaults = {layout_strategy = 'center'} }
```

Here's the error message:
```
E5108: Error executing lua ...lan/code/telescope.nvim/lua/telescope/config/resolve.lua:103: attempt to perform arithmetic on a nil value
```

After some poking around, I discovered the path of function calls:

```
resolve.lua:103                   return math.floor(val * select(selector, ...))
  from resolve.lua:132            return v(3, val)
  from layout_strategies.lua:141  local height
  from pickers.lua:149            local getter
```

The error comes from the default `results_height` being 1, which is interpreted as a percentage when it is expected to be a number.

**Comment by tjdevries** [comment]
Does the recent commit fix this for you?
