### ISSUE TITLE
ANSI Escape Sequences are not getting parsed correctly

### ISSUE THREAD

**Issue by krkhan** [nvim-lua/telescope.nvim#160]
![image](https://user-images.githubusercontent.com/697967/95533319-b8331800-0997-11eb-88d1-02f11237234b.png)

I have `bat` in my path. This was working before but broke when I updated to c2c4626 . I'll git-bisect later to find the commit that broke the display.

**Comment by tjdevries** [comment]
What file is this? What do you expect to show?

Can you give me your OS information as well?

**Comment by krkhan** [comment]
@tjdevries It was a `.go` file. I am getting the same for all files (rust/go/bash). Tried on Gentoo/Arch/Fedora/Ubuntu and saw same behavior in all of them.

Looks like fa17b37dad05a2928ee64bb53a8be8a36ee2de14 broke it. The bat command invocation is wonky now:

```
/home/kamran.khan/.artifacts/bin/bat --pager less -S --style=plain --color=always --paging=always -- /home/kamran.khan/go/src/git.soma.salesforce.com/Kuleana/moria/pkg/radius/radius.go
```

**Comment by tjdevries** [comment]
OK, you should be able to now set (in your `setup`) `use_less = false`, which should disable using `less` I think.

Let me know if that fixes the issue.

**Comment by krkhan** [comment]
@tjdevries viola! Works like a charm, thanks for the quick fix!

**Comment by tjdevries** [comment]
I'm glad I'm not.... `use_less` 😂
