### ISSUE TITLE
How to turn-off deoplete/autocomplete suggestions when typing

### ISSUE THREAD

**Issue by krkhan** [nvim-lua/telescope.nvim#161]
Currently, if I start typing in the search field deoplete suggestions keep popping up:

![image](https://user-images.githubusercontent.com/697967/95542743-7dd37600-09ab-11eb-8c64-b6236a03347c.png)

Which is mildly-distracting but fine. However, when I select an entry it then puts the partially entered text into the document:

![image](https://user-images.githubusercontent.com/697967/95542807-a3607f80-09ab-11eb-8e2b-93a43871156d.png)

This doesn't happen if deoplete suggestions are not kicking in. I suspect there's an easy way to turn this off which should probably be in the README.

**Comment by krkhan** [comment]
This helps:

```
autocmd FileType TelescopePrompt call deoplete#custom#buffer_option('auto_complete', v:false)
```

**Comment by taketwo** [comment]
If you are using `completion-nvim` and have completion enabled in _every_ buffer through `BufEnter` autocommand, you may selectively disable completions in Telescope window by adding `'TelescopePrompt' : [ ]` to your chain completion list setting `g:completion_chain_complete_list`.

**Comment by galbacarys** [comment]
For anyone using Asyncomplete:


```
au FileType TelescopePrompt let b:asyncomplete_enable=0
```

fixes the issue. This also helps if you're dealing with the "Not Allowed"/"E523" error, which is basically due to asyncomplete (or another autocomplete plugin) and telescope fighting to set buffer state (I think) which messes with nvim in strange ways.
