### ISSUE TITLE
why live_grep can't find the string `completion_next_source`

### ISSUE THREAD

**Issue by smartding** [nvim-lua/telescope.nvim#166]
I was looking for the string `completion_next_source` in the source code of `nvim-lua/completion-nvim`, I knew the string is somewhere, but surprisingly `live_grep` couldn't find it.

I thought the `.vim` in `.gitignore` was getting in the way (because the string is in `completion.vim`), so I deleted it. But live_grep still couldn't find the string. I ran `rg --color=never --no-heading --with-filename --line-number --column --smart-case completion_next_source` in command line, it found the string! 

So what happend?  why `live_grep` can't find the string `completion_next_source`?

**Comment by tami5** [comment]
relates to ongoing issues with live_grep #149 #151

**Comment by elianiva** [comment]
I think this has been fixed. Left screenshot is using the default sorter and the right one is using `fzy` sorter. They both found `completion_next_source`.

![image](https://user-images.githubusercontent.com/51877647/96693212-27096b80-13b1-11eb-88f4-15618073a3b1.png)

**Comment by smartding** [comment]
> I think this has been fixed. Left is using the default sorter and the right one is using `fzy` sorter. They both found `completion_next_source`.
> 
> ![image](https://user-images.githubusercontent.com/51877647/96693212-27096b80-13b1-11eb-88f4-15618073a3b1.png)

yes, it's fixed now.
BTW, how did you get the coloring in the result?

**Comment by elianiva** [comment]
Telescope has some highlight groups that you can change. If you want to check mine, [here you go](https://github.com/elianiva/dotfiles/blob/cc02614079a60b46f2de15719857213af52124a5/nvim/.config/nvim/lua/modules/appearances.lua#L50-L54).

**Comment by smartding** [comment]
> Telescope has some highlight groups that you can change. If you want to check mine, [here you go](https://github.com/elianiva/dotfiles/blob/cc02614079a60b46f2de15719857213af52124a5/nvim/.config/nvim/lua/modules/appearances.lua#L50-L54).

thanks
