### ISSUE TITLE
Wrong path in git file picker

### ISSUE THREAD

**Issue by p00f** [nvim-lua/telescope.nvim#174]
![Screenshot from 2020-10-12 17-36-27](https://user-images.githubusercontent.com/36493671/95746505-829e6f80-0cb4-11eb-9db3-71586a1ed9c6.png)

telescope can't find the files because it is looking in the wrong place

sorry for the handwriting

**Comment by p00f** [comment]
I tried both
1) nvim `~/stuff/adwaita-dracula/Adwaita-Dracula/gnome-shell/gnome-shell.css`
2) open nvim, then `:e stuff/adwaita-dracula/Adwaita-Dracula/gnome-shell/gnome-shell.css`

neovim version `NVIM v0.5.0-741-gca6815115`

**Comment by p00f** [comment]
Now updated to `NVIM v0.5.0-751-gd198aa511`, I still have this issue

**Comment by tjdevries** [comment]
Yeah, you may want to use find files in the mean time. That should work for you.

**Comment by p00f** [comment]
ohk
