### ISSUE TITLE
Option to enable default devicons

### ISSUE THREAD

**Issue by elianiva** [nvim-lua/telescope.nvim#177]
Do you think it's a good idea to give the user an option whether or not telescope use the default icon for a filetype that doesn't have an icon? In my case it's `svelte`

nvim-web-devicons has an option to enable the default icon if the icon is not available for that filetype. Personally, I prefer having the default icon rather than having an empty space. Here's a comparison between them, left one is using the default icon and the right one isn't.

![Group 38](https://user-images.githubusercontent.com/51877647/96358120-d6361080-112d-11eb-9a74-ce3eaa33801a.png)

**Comment by tjdevries** [comment]
This is a good idea. You might actually be able to do this with the devicons library we use as well. Are you interested in implementing?

**Comment by elianiva** [comment]
I was going to implement this before I made this issue but I have no idea how to bring the config option from `.setup{}` and use it on `make_entry.lua`

What I did right now is just hardcode it like this
```lua
local icon_display = (devicons.get_icon(filename, string.match(filename, '%a+$'), { default = true }) or ' ') .. ' ' .. display
```
