### ISSUE TITLE
[Feature Request] auto zz after jump

### ISSUE THREAD

**Issue by smartding** [nvim-lua/telescope.nvim#182]
telescope can easily jump to definition, but that definition can be near the top or bottom of screen. Is there any to configure telescope to move current line to the center of screen after jump?

**Comment by tjdevries** [comment]
do you want to do this for every `goto` action (edit, tabsplit, etc.)?

**Comment by smartding** [comment]
> do you want to do this for every `goto` action (edit, tabsplit, etc.)?

I only use `edit` most of the time, but I think this "auto center" feature makes sense for `tabs` and `splits` too.

**Comment by tjdevries** [comment]
What if I allowed you to do things like add two actions together.

actions.goto_file + actions.center

Then you could define your own custom map for enter that does this. Would that be good?

**Comment by tjdevries** [comment]
I don't want to add a million config options, that makes things very difficult to control. And I don't want to make a function for every possibility.

**Comment by smartding** [comment]
> What if I allowed you to do things like add two actions together.
> 
> actions.goto_file + actions.center
> 
> Then you could define your own custom map for enter that does this. Would that be good?

That's good enough.

**Comment by Conni2461** [comment]
I got this working in #204. I'm not sure if this is what you had in mind, @tjdevries.
Currently `actions.goto_file_selection_edit + actions.center` is already set for `<CR>` but i would remove this and add documentation, so users can configure it themselves.
Could you try it @smartding?

**Comment by smartding** [comment]
> I got this working in #204. I'm not sure if this is what you had in mind, @tjdevries.
> Currently `actions.goto_file_selection_edit + actions.center` is already set for `<CR>` but i would remove this and add documentation, so users can configure it themselves.
> Could you try it @smartding?

I tried `["<CR>"] = actions.goto_file_selection_edit + actions.center` with `live_grep`, `treesitter`, `lsp_document_symbols` and `lsp_workspace_symbols` of `builtin`,  it worked.

**Comment by smartding** [comment]
Can we simply add the `zz` command in key mapping? e.g.
```lua
  vim.api.nvim_set_keymap('n', '<leader>e', ":lua require('telescope.builtin').lsp_document_symbols();vim.api.nvim_command(':normal zz')<CR>", opts)
```

**Comment by Conni2461** [comment]
Thanks for testing.
Sure you could do that, but `zz` would always be executed when the window closes, even if you close the window with `<esc><esc>`.
You also have to do this for every mapping which can be quiet inconvenient.

After #204 is merged you can just do something like this in your setup
```lua
require('telescope').setup {
  defaults = {
    mappings = {
      i = {
        ["<CR>"] = actions.goto_file_selection_edit + actions.center
      },
      n = {
        ["<CR>"] = actions.goto_file_selection_edit + actions.center
      },
    },
  }
}
```
which would work with every `builtin`(also with the `Telescope` commands and not only with the specific mapping) and only when you confirm a selection with `<CR>`.

**Comment by smartding** [comment]
> Thanks for testing.
> Sure you could do that, but `zz` would always be executed when the window closes, even if you close the window with `<esc><esc>`.
> You also have to do this for every mapping which can be quiet inconvenient.
> 
> After #204 is merged you can just do something like this in your setup
> 
> ```lua
> require('telescope').setup {
>   defaults = {
>     mappings = {
>       i = {
>         ["<CR>"] = actions.goto_file_selection_edit + actions.center
>       },
>       n = {
>         ["<CR>"] = actions.goto_file_selection_edit + actions.center
>       },
>     },
>   }
> }
> ```
> 
> which would work with every `builtin`(also with the `Telescope` commands and not only with the specific mapping) and only when you confirm a selection with `<CR>`.

With `<CR>` mapped to `actions.goto_file_selection_edit + actions.centerwhat`, what happens when popup window is closed with `<esc><esc>`?  Will `actions.center` still be executed?

**Comment by Conni2461** [comment]
No only on `<CR>`, so it will also not be executed on `<C-x>`, `<C-v>` and `<C-t>` (split, vsplit and tab). If you want this you need to extend my example like this
```lua
require('telescope').setup {
  defaults = {
    mappings = {
      i = {
        ["<CR>"] = actions.goto_file_selection_edit + actions.center,
        ["<C-x>"] = actions.goto_file_selection_split + actions.center,
        ["<C-v>"] = actions.goto_file_selection_vsplit + actions.center,
        ["<C-t>"] = actions.goto_file_selection_tab + actions.center,
      },
      n = {
        ["<CR>"] = actions.goto_file_selection_edit + actions.center,
        ["<C-x>"] = actions.goto_file_selection_split + actions.center,
        ["<C-v>"] = actions.goto_file_selection_vsplit + actions.center,
        ["<C-t>"] = actions.goto_file_selection_tab + actions.center,
      },
    },
  }
}
```
So basically if you want `actions.center` to run after a specific mapping you actually have to set it.

**Comment by Conni2461** [comment]
@smartding We do `center` now on default. So you don't have to configure anything.

**Comment by smartding** [comment]
> @smartding We do `center` now on default. So you don't have to configure anything.

Checking the diff was the first thing I did. Thanks.

**Comment by smartding** [comment]
@Conni2461, how do I map a key to multiple lua calls? I'm trying to center cursor line after go to definition, tried the config below, doesn't work:
```lua
  vim.api.nvim_buf_set_keymap(
    0, 'n', 'gd',
    '<cmd>lua vim.lsp.buf.definition();vim.api.nvim_command(":normal! zz")<CR>', opts
  )
```

**Comment by tjdevries** [comment]
Definition is async, so that won't work.

**Comment by collinvandyck** [comment]
@smartding I have a similar setup to what you're trying to do. I found that this augroup does most of what I wanted:

```
vim.cmd([[
augroup KeepCentered
  autocmd!
  autocmd CursorMoved * normal! zz
augroup END
]])
```

So no matter how you jump (LSP-driven/async or not), when your cursor moves, it will be centered.
