### ISSUE TITLE
Cannot enter selected file with the enter key from insert mode

### ISSUE THREAD

**Issue by davidv171** [nvim-lua/telescope.nvim#183]
So either the docs are unclear what <CR> (I assume it's supposed to be the ENTER key) is, or there's a bug:

Steps to reproduce:

1. Run:
`:lua require'telescope.builtin'.find_files(require('telescope.themes').get_dropdown({}))<cr>`

2. Type the text into the box (from insert mode)

3. Press enter

4. Text disappears, selections don't update as I type anymore, I cannot reach the text I've entered before. But apparently it's still there. The split and tab keybinds work fine, a custom <c-e> keybind also works fine. As does entering normal mode and pressing enter. 

```lua
require('telescope').setup{
  defaults = {
    -- Example:
    shorten_path = true -- currently the default value is true

    mappings = {
	["<c-e>"] = actions.goto_files_selection,
  }
}
```
This is all my config on it so far.

**Comment by tjdevries** [comment]
Do you have your own mapping on enter for insert mode? You may be overriding the mapping.

**Comment by davidv171** [comment]
Yep, after having it work just fine on another machine, this is very likely my own error.
