### ISSUE TITLE
find_files gives illegal option -- t: No such file or directory

### ISSUE THREAD

**Issue by KaiSpencer** [nvim-lua/telescope.nvim#193]
Remap:
`nnoremap <Leader>p <cmd>lua require'telescope.builtin'.find_files{}<CR>
`

UI shows 
`cat: /Users/kai/find: illegal option -- t: No such file or directory                                
                                                                                   ││[Process exited 1]`

MacOS
NVIM v0.5.0-a22fe09
Build type: Release
LuaJIT 2.0.5
<img width="1250" alt="Screenshot 2020-10-26 at 21 46 43" src="https://user-images.githubusercontent.com/51139521/97232270-c1641780-17d4-11eb-90db-0a3c5b1995b1.png">

**Comment by arclaxton** [comment]
I had the same trouble. Installing [fd](https://github.com/sharkdp/fd) and calling invoking finder like `lua require'telescope.builtin'.find_files{find_command={"fd"}}` makes it work as advertised for me

**Comment by Conni2461** [comment]
Thanks for reporting this. I could not reproduce this on Linux but i think this is because find expects the directory path at the first argument. It might be that MacOS find build is here more striked than Linux.
Could you try #199

**Comment by KaiSpencer** [comment]
> Thanks for reporting this. I could not reproduce this on Linux but i think this is because `find` expects the directory path as first argument. It might be that MacOS `find` build is here more strict than Linux.
> Could you try #199

Confirmed this fixed the issue.
