### ISSUE TITLE
[Feature Request]: setting options with global variables

### ISSUE THREAD

**Issue by tami5** [nvim-lua/telescope.nvim#194]
It would be much much simpler for new users to have setup function variables set through builtin global variables.

```lua
    defaults.sorting_strategy = vim.api.nvim_get_var('tele_sorting_strategy') or "descending"
    defaults.layout_strategy = vim.api.nvim_get_var('tele_layout_strategy') or "horizontal"
```

Thanks

**Comment by tjdevries** [comment]
I do not want to use global variables for configuration :) 

I think the `telescope.setup` with it's `default` keys are easy enough to use and provide much much better flexibility for me as the developer and for you as the user.

There is currently a problem with documentation, but I will add examples of how to configure all the little details later :)

I'd like to close this, as I would not support using vim's global variables. is that OK?
