### ISSUE TITLE
preview not displaying for file which has spaces in name

### ISSUE THREAD

**Issue by SubeetKD** [nvim-lua/telescope.nvim#20]
![Screenshot from 2020-09-02 13-12-58](https://user-images.githubusercontent.com/34621179/91951273-3c9dd580-ed1e-11ea-932b-b87f1ba52c50.png)

**Comment by tjdevries** [comment]
This is with builtin git files?

When you select one, does it edit the file correctly?

**Comment by SubeetKD** [comment]
Yes it's in git repository and when I select it opens it. Only preview is showing.
