### ISSUE TITLE
Add ability to ignore / do_not_preview certain file names

### ISSUE THREAD

**Issue by tjdevries** [nvim-lua/telescope.nvim#205]

**Comment by erkrnt** [comment]
Just to add some context - would like a way to filter out files or patterns that I don't want to appear in the preview for security reasons, etc.

Something to be able to configure values like `*.secrets.*` or `my_folder/`.

**Comment by tjdevries** [comment]
OK, this has been implemented I think. You can use the new option described in the readme :)

@erkrnt let me know if you have any troubles with it.

**Comment by tjdevries** [comment]
(This will prevent you from selecting them in telescope, if you want something else, we can probably implement that too)

**Comment by erkrnt** [comment]
![subscribe to teej_dv on twitch](https://i.giphy.com/media/kyv1M0YschycH4413C/source.gif)

@tjdevries worked like a charm - thank you sir!

**Comment by tjdevries** [comment]
@theprimeagen you may want to know about this feature as well

**Comment by sivaplaysmC** [comment]
pls tell how to use this feautre pls
