### ISSUE TITLE
Error with nvim-web-devicons: nvim_command must not be called in a lua loop callback

### ISSUE THREAD

**Issue by sharksforarms** [nvim-lua/telescope.nvim#211]
I am getting the follow error when first opening telescope with the [nvim-web-devicons](https://github.com/kyazdani42/nvim-web-devicons) plugin.

```
Error executing luv callback:
...nvim/plugged/nvim-web-devicons/lua/nvim-web-devicons.lua:850: E5560: nvim_command must not be called in a lua loop callback
```

I think this is caused by the following call:
https://github.com/nvim-lua/telescope.nvim/blob/master/lua/telescope/make_entry.lua#L18

I thought it was a `nvim-web-devicons` issue: https://github.com/kyazdani42/nvim-web-devicons/pull/27

(I don't have much nvim/lua experience to know what a proper solution is)

**Comment by tjdevries** [comment]
Does the latest commit fix the problem? If not, you can open this again.

**Comment by tami5** [comment]
@tjdevries broke mine though :D

First error

`...k/packer/opt/telescope.nvim/lua/telescope/make_entry.lua:14: attempt to call field 'has_loaded' (a nil value)`

Then my mappings breaks:

`E5108: Error executing lua /home/tami/.config/nvim/lua/module/prompts.lua:31: attempt to index local '_1_' (a nil value)`

and Telescope command

`Error executing lua ...k/packer/opt/telescope.nvim/lua/telescope/make_entry.lua:14: attempt to call field 'has_loaded' (a nil value)`

Please revert

**Comment by tjdevries** [comment]
Have you updated devicons?

**Comment by tami5** [comment]
Damn it not again, yes @tjdevries updating devicons fixed my issue. That's it I'm switching back to packer.nvim :D

**Comment by sharksforarms** [comment]
Confirmed working
