### ISSUE TITLE
telescope tries to show preview for binary files

### ISSUE THREAD

**Issue by ElPiloto** [nvim-lua/telescope.nvim#223]
Would be helpful if telescope knew not to try to preview arbitrary binary files as it leaves a bunch of garbage characters on the screen.   I've seen this functionality implemented by checking XDG MIME type, but unclear how general that solution can be on all platforms.

**Comment by Conni2461** [comment]
Hey thanks for the report. Just to be clear this only happens when `cat` is used?!
I got a fix up and running. Could you test #224

**Comment by ElPiloto** [comment]
Yep, it worked: https://snipboard.io/S0qDzF.jpg Although maybe you don't want that `[Process exited 0]` bit there.  Either way, thanks for the quick fix :smiley:

**Comment by Conni2461** [comment]
That is actually a thing of `termopen`, which is use to connect a "pseudo-terminal session" to a buffer (see `:help termopen`). When a command is done `[Process exited 0]` is printed, with the corresponding exit code. So previewing a small file with `cat` will also show this.

**Comment by ElPiloto** [comment]
Oh, cool. TIL.

**Comment by gbrlsnchs** [comment]
This is happening again, now when using the tree-sitter preview. Depending on the size of the binary file, Neovim completely freezes.

**Comment by Conni2461** [comment]
Yes i know because i haven't found the time to write a good implementation. I thought we should rely on a platform independent binary detection in lua. A way to configure this would be (because you can override the filereading):
```lua
local previewers = require('telescope.previewers')
local Job = require('plenary.job')
local new_maker = function(filepath, bufnr, opts)
  filepath = vim.fn.expand(filepath)
  Job:new({
    command = 'file',
    args = { '--mime-type', '-b', filepath },
    on_exit = function(j)
      local mime_type = vim.split(j:result()[1], '/')[1]
      if mime_type == "text" then
        previewers.buffer_previewer_maker(filepath, bufnr, opts)
      else
        -- maybe we want to write something to the buffer here
        vim.schedule(function()
          vim.api.nvim_buf_set_lines(bufnr, 0, -1, false, { 'BINARY' })
        end)
      end
    end
  }):sync()
end

require('telescope').setup {
  defaults = {
    buffer_previewer_maker = new_maker,
  }
}
```

I wanted to add some other things to `buffer_previewer_maker` so i might end up using this method and caching if file is binary or not. At least per picker run. So if i select the same file twice it will not run `file --mime-type - b filepath` twice
