### ISSUE TITLE
Should add ability to specify action upon selecting a item in the list

### ISSUE THREAD

**Issue by bryall** [nvim-lua/telescope.nvim#25]
for example select something from the list and append it to the current place in the buffer

**Comment by tjdevries** [comment]
Hey @bryall I'm not sure if you've seen the changes recently, but does the new `entry_maker` pattern + allowing you to specify mappings in `attach_mappings` work for you?

I can try and write something up about how to do this if you want.

**Comment by bryall** [comment]
i like the action mapping code added. but the only thing preventing me from getting this working is finding the current buffer. is there a way to pass variables to the action function?  i see it takes a prompt buffer.

**Comment by tjdevries** [comment]
current buffer as in "where you started" or current buffer "where the preview is" or what? I'm not sure which buffer you mean?

Can you add a code snippet of what you\'d like to do? I can probably just figure out what needs to happen to make it work the way you want (pseudo-code for parts that don't exist yet is good)

**Comment by bryall** [comment]
where you started

- type an action in the map
- insert the entry into the original buffer at your current cursor position

so what I am doing right now is I took your insert_value action and trying to write a string into the original function

**Comment by tjdevries** [comment]
@bryall Is there anything more you need here? I'm not sure what you need now.

**Comment by bryall** [comment]
I think telescope has what I need, I have a bug on my end that I am tracking down to test , will close for now
