### ISSUE TITLE
Current issues.

### ISSUE THREAD

**Issue by rockerBOO** [nvim-lua/telescope.nvim#4]
Error when trying to open telescope really early in the startup.
```
E5108: Error executing lua ...ig/nvim/plugged/telescope.nvim/lua/telescope/pickers.lua:307: attempt to index local '
preview_opts' (a nil value)
```
Trying to access references through `lsp_references()`. Maybe no references? Also this error happens before the LS fully loads.
```
E5108: Error executing lua ...ig/nvim/plugged/telescope.nvim/lua/telescope/builtin.lua:120: bad argument #1 to 'pairs' (table expected, got nil)
```

Showing me bumpling through. Note the `.gitignore` where it is almost showing the correct (IMO) but then it does additional fuzzing after matching on the filename. 

https://www.youtube.com/watch?v=2fQ8KcfWSS8

**Comment by tjdevries** [comment]
(First youtube video):

Previewer should check if the file is deleted. Or perhaps `git ls-files` should not show it (probably a setting).

**Comment by rockerBOO** [comment]
This error occurs after opening the menu, and closing it (:q) (which produces the first error in this issue). Then trying to close again produces this error.
```
Error detected while processing BufLeave Autocommands for "<buffer=19>":
E5108: Error executing lua ...ig/nvim/plugged/telescope.nvim/lua/telescope/pickers.lua:516: attempt to inde
x local 'picker' (a nil value)
```
