### ISSUE TITLE
Closing the buffer can send you back to a different buffer from where you came

### ISSUE THREAD

**Issue by brandoncc** [nvim-lua/telescope.nvim#41]
Steps to reproduce:

- Open one window on top of the other
- Make the bottom window active
- Run `:lua require'telescope.builtin'.fd{}`
- Hit escape twice

You are now in the top window. It would be nice if it sent me back to the window I came from, especially if I exit without selecting any of the items.

**Comment by tjdevries** [comment]
Hmmm...  I thought I fixed this. Does this still happen with the most recent version?

**Comment by brandoncc** [comment]
Yes, it happens to me in the latest version.

**Comment by tjdevries** [comment]
Think I fixed it with latest commit.

Realized that `actins.close` didn't send you back to original window.

**Comment by tjdevries** [comment]
(Open this if it's not working for you)
