### ISSUE TITLE
Set a filetype?

### ISSUE THREAD

**Issue by brandoncc** [nvim-lua/telescope.nvim#50]
I would like to map `<ESC>` to `<ESC><ESC>` in insert mode in the search field of a telescope buffer. I think we would need to set a filetype while in that input, what do you think about a telescope-buffer filetype or something?

**Comment by tjdevries** [comment]
We have `attach_mappings` already for telescope. This should allow you to do this.

However, a filetype would probably be good as well. I can add this.

**Comment by Melkster** [comment]
Sorry if this is a dumb question, but how would I use `attach_mappings` to map `<ESC>` to `<ESC><ESC>`? I can't really find anything describing how to use `attach_mappings`.

**Comment by Conni2461** [comment]
@Melkster https://github.com/nvim-telescope/telescope.nvim/wiki/Configuration-Recipes#mapping-esc-to-quit-in-insert-mode

**Comment by Melkster** [comment]
@Conni2461 Thank you! There is no `actions.close` in `:h telescope.actions`, maybe it should be added?
