### ISSUE TITLE
Feature Request: Add Buffer List

### ISSUE THREAD

**Issue by cjgratacos** [nvim-lua/telescope.nvim#57]
It would be awesome if we can have a list of the current buffers. Something similar to the FZF Buffers.

**Comment by the-codingguy** [comment]
We do have that you can use - `:lua require'telescope.builtin'.buffers{}` probably have to add documentation for this.

**Comment by Conni2461** [comment]
I have already added documentation in #32.
Besides the opt that allows you to also display unloaded buffers.

**Comment by tjdevries** [comment]
This should work now: `:lua require'telescope.builtin'.buffers{}` improvements are possible in the future, but should be good.
