### ISSUE TITLE
Seperate out the lsp functionality (like - references) and add a functionality to navigate document symbol.

### ISSUE THREAD

**Issue by the-codingguy** [nvim-lua/telescope.nvim#72]
Separating the `lsp` functionalities from `builtin's` to keep it minimal and have a potential to add more `lsp` related features. Such as `vim.lsp.buf.document_symbol()`

**Comment by clason** [comment]
@the-codingguy both `document_symbol` and `workspace_symbol` are already supported :)

https://github.com/nvim-lua/telescope.nvim/blob/3d423a3b592ab49cbe89a4bf88d2cab6bd663509/lua/telescope/builtin.lua#L159

https://github.com/nvim-lua/telescope.nvim/blob/3d423a3b592ab49cbe89a4bf88d2cab6bd663509/lua/telescope/builtin.lua#L190

**Comment by tjdevries** [comment]
Yeah, I think we can close this.

At some point, we will probably split builtin into multiple files and then just have built be the thing that exposes all of them.
