### ISSUE TITLE
Some weirdness when opening a file via telescope

### ISSUE THREAD

**Issue by Anrock** [nvim-lua/telescope.nvim#75]
Not sure if this is telescope fault or treesitter. 

So basically when you open a file via telescope `find_files` treesitter highlighting is not working until you manually run `TSBufEnable highlight`. Also, path to file is absolute in statusline and after you edited the file and trying to save nvim goes `E13: File exists (add ! to override)`

Opening same file with `:e` doesn't have those problems - path is relative to cwd and highlighting is working.

**Comment by tjdevries** [comment]
Ok, thanks for the report.

Do you happen to know what autocommand nvim tree sitter is expecting when opening the file? My guess is I'm somehow not triggering that when we open the file and I could open that.

Is the file already open in neovim before you open it in find_files or no?

**Comment by Anrock** [comment]
> Do you happen to know what autocommand nvim tree sitter is expecting when opening the file?

No, unfortunately I don't know. I'm just trying to migrate my nvim setup to all the lua goodies, so this is basically first-experience-report :)

> Is the file already open in neovim before you open it in find_files or no?

No, it's not. I'm just `cd myproject;  nvim` and then call `find_files` and open file from telescope.

**Comment by Anrock** [comment]
Okay, it's really weird. I have this problem on my macos machine with neovim HEAD from today and I don't have this problem on my linux machine with neovim HEAD compiled yesterday. Could be actually nvim-related problem. 

I'm gonna do some more cross-checks to find out what's going.

**Comment by tjdevries** [comment]
Yeah, I just experienced this problem today as well -- it may be something that `nvim-treesitter` or core needs to fix. Thanks for reporting (and I'll see if I can track it down as well if I can find some time to do so).

I just disabled treesitter for myself right now. Might re-enable in a week or so after they have a bit more time to iron out some of the rough edges.

**Comment by Anrock** [comment]
Welp, I've rebuilt neovim head today on my mac machine and treesitter problem along with saving problem is gone now. The only thing left is that opened file still has absolute path while I expect it to be relative to cwd.

**Comment by tjdevries** [comment]
(if that's cool and everything else seems fine, closing this issue would be great)

**Comment by Anrock** [comment]
Sure!

**Comment by theherk** [comment]
I'm experiencing this same issue. Open with `:e file`, can save. Open with `:Telescope find_files<cr>`, can't save without `!`. Very strange.
