### ISSUE TITLE
bat preview doesn't work on telescope.builtin.quicklist after helpgrep

### ISSUE THREAD

**Issue by gagbo** [nvim-lua/telescope.nvim#78]
This is to be expected : the file name in the quickfix list is just the name of the file somewhere in doc files, Bat has no idea where to find the files.

Probably not easy to "fix" as well, since a quickfix list doesn't really carry the extra information about which base folder you're supposed to use to extend the filenames does it ?

**Comment by tjdevries** [comment]
We could instead try and make a specific thing for helpgrep -- is that your main goal for what you'd like to see?

I can also look at improving the filename detection in the quickfix previewer (obviously not sure if it will be possible to perfectly detect).

I'm open to other ideas as well :)

**Comment by gagbo** [comment]
I think having a `require("telescope.builtin").helpgrep` might be better. 

I think that's the only case where the quickfix list is filled using files *not* from the current working directory (maybe vimgrep has an option for that, but if a user is considering that they could just fzf their projtect instead)

So just for this one we could use a special function. Edge case to consider: how are rendered the result if the hit comes from a file under `rtp/pack/?/?/package/doc/package-special-doc-file.txt` ? Can we actually extract the absolute path for `bat`, or does helpgrep only return `package-special-doc-file.txt` and "good luck with that" ?

**Comment by tjdevries** [comment]
I think I've fixed.

Should work after helpgrep now.

**Comment by tjdevries** [comment]
(please let me know if it's not working though)
