### ISSUE TITLE
bug: Doubling up on the same line

### ISSUE THREAD

**Issue by rockerBOO** [nvim-lua/telescope.nvim#80]
![2020-09-15-103856_4480x1440_scrot](https://user-images.githubusercontent.com/15027/93225022-c2b71480-f73f-11ea-9611-4bbe749cc974.png)

This happens a lot. It is not consistent in what it doubles up.

**Comment by tjdevries** [comment]
Is this still happening a lot for you?

I haven't been able to reproduce on my machine. I've also added a lot of updates to plenary, so maybe it won't occur anymore.

**Comment by rockerBOO** [comment]
I've been using the prime sorter and I haven't seen it with that. I also haven't been doing coding the few days so I haven't been able to really test it. 

I would say it is resolved enough that if I see it again I will remake an issue.
