### ISSUE TITLE
Feature request: Option to prefill the live_grep with <cword>

### ISSUE THREAD

**Issue by urandom** [nvim-lua/telescope.nvim#93]
Hi,

I'd like to request an option to the live_grep, that, when true, would use the <cword> as the initial grep, much like grep_string does by default

**Comment by tjdevries** [comment]
You can do this part already if you want manually.

Use the `default_text` options.

`live_grep { default_text = vim.fn.expand("<cword>") }` should probably work.

Let me know if it doesn't.

**Comment by urandom** [comment]
Works great, thanks

**Comment by tjdevries** [comment]
Glad to help :)
