### ISSUE TITLE
builtin.buffers() does not show hidden buffers when reopening a Session

### ISSUE THREAD

**Issue by ruifm** [nvim-lua/telescope.nvim#97]
# Steps to reproduce

1. Open some buffers, some of them hidden, some of them in the current window.
2. Save current session (I use [tpope's vim-obsession plugin](https://github.com/tpope/vim-obsession)) for this (`:Obsession`)
3. Close nvim
4. Reopen session with `nvim -S`
5. `:lua require'telescope.builtin'.buffers()`

# Actual behavior

`telescope` does not show hidden buffers, only lists buffers currently visible.

# Expected behavior

`telescope` should list all buffers, hidden or not.
As a comparison, this is the behavior of `:Buffers` in the [fzf.vim plugin](https://github.com/junegunn/fzf.vim)

**Comment by Conni2461** [comment]
Hey thanks for the report. #32 added this behavior with an opt variable and is documented [here](https://github.com/nvim-lua/telescope.nvim#vim).
Basically you would run `lua require'telescope.builtin'.buffers{ show_all_buffers = true }`.
Currently the opt default is false but we could change that depending on how @tjdevries feels about it.

Let me know if this works. I have not tested it with `vim-obsession`.

**Comment by ruifm** [comment]
> Hey thanks for the report. #32 added this behavior with an opt variable and is documented [here](https://github.com/nvim-lua/telescope.nvim#vim).
> Basically you would run `lua require'telescope.builtin'.buffers{ show_all_buffers = true }`.
> Currently the opt default is false but we could change that depending on how @tjdevries feels about it.
> 
> Let me know if this works. I have not tested it with `vim-obsession`.

It works, thanks.

**Comment by ruifm** [comment]
> Currently the opt default is false but we could change that depending on how @tjdevries feels about it.

Just leaving my 2 cents here @tjdevries : defaulting this option to false does not make sense to me. If the buffers are visible, one can just navigate to them. One upside of a buffer-based workflow (instead of using tabs like in other editors) is that one could have hundreds of hidden buffers and still navigate through them seamlessly.

**Comment by tjdevries** [comment]
I see what you're saying.

For now I think I will leave it as is. At some point, I may add more easy default configuration for people for this, but I have some bugs I have to fix first :laughing:
