### ISSUE TITLE
builtin.buffers() split/vsplit/tab mappings do not work

### ISSUE THREAD

**Issue by ruifm** [nvim-lua/telescope.nvim#98]
# Steps to reproduce

1. Open a buffer
2. `:lua require'telescope.builtin'.buffers()`
3. Select a buffer and press `<c-x>` or `<c-v>` or `<c-t>`

# Actual behavior

After a small hang, the selected buffer opens in-place of the current one.

# Expected behavior

It should open the selected buffer in a split/vsplit/tab accordingly as stated in [telescope.nvim#mappings](https://github.com/nvim-lua/telescope.nvim#mappings). The same issue does not seem to occur with other builtin pickers.

**Comment by Conni2461** [comment]
Hey thanks for your report. I just implemented a "hack", i'm not 100% sure about.
Could you test #99.

**Comment by ruifm** [comment]
Yes, it fixes it!
